package module05_array;

public class Array05 {
    static void main(String[] args) {
        // don't try this , it is unusual method ;
        int[] arr = {1,2,3,4,5};
        // printing like this !!
        System.out.println(arr); // no give hashcode : [I@27716f4

        //this is a hashcode, use for loop or for each ok for printing array
        // what is meaning of that ?
        // The [ Symbol: This tells you that the object is a One-Dimensional Array.
        // The I Character: This represents the internal code for the int primitive data type.
        // The @27716f4 Part: This is the Unsigned Hexadecimal Hashcode generated by the JVM.
    }
}
